// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/subscription.service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dtos "subscription_service/internal/dtos"
	models "subscription_service/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockSubscriptionService is a mock of SubscriptionService interface.
type MockSubscriptionService struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionServiceMockRecorder
}

// MockSubscriptionServiceMockRecorder is the mock recorder for MockSubscriptionService.
type MockSubscriptionServiceMockRecorder struct {
	mock *MockSubscriptionService
}

// NewMockSubscriptionService creates a new mock instance.
func NewMockSubscriptionService(ctrl *gomock.Controller) *MockSubscriptionService {
	mock := &MockSubscriptionService{ctrl: ctrl}
	mock.recorder = &MockSubscriptionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionService) EXPECT() *MockSubscriptionServiceMockRecorder {
	return m.recorder
}

// CreateSubscriptionPlan mocks base method.
func (m *MockSubscriptionService) CreateSubscriptionPlan(ctx context.Context, subscription *models.Subscription) (*models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscriptionPlan", ctx, subscription)
	ret0, _ := ret[0].(*models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscriptionPlan indicates an expected call of CreateSubscriptionPlan.
func (mr *MockSubscriptionServiceMockRecorder) CreateSubscriptionPlan(ctx, subscription interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscriptionPlan", reflect.TypeOf((*MockSubscriptionService)(nil).CreateSubscriptionPlan), ctx, subscription)
}

// DeleteSubscriptionPlan mocks base method.
func (m *MockSubscriptionService) DeleteSubscriptionPlan(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscriptionPlan", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscriptionPlan indicates an expected call of DeleteSubscriptionPlan.
func (mr *MockSubscriptionServiceMockRecorder) DeleteSubscriptionPlan(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscriptionPlan", reflect.TypeOf((*MockSubscriptionService)(nil).DeleteSubscriptionPlan), ctx, id)
}

// GetSubscriptionPlan mocks base method.
func (m *MockSubscriptionService) GetSubscriptionPlan(ctx context.Context, id string) (*models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionPlan", ctx, id)
	ret0, _ := ret[0].(*models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionPlan indicates an expected call of GetSubscriptionPlan.
func (mr *MockSubscriptionServiceMockRecorder) GetSubscriptionPlan(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionPlan", reflect.TypeOf((*MockSubscriptionService)(nil).GetSubscriptionPlan), ctx, id)
}

// ListSubscriptionPlans mocks base method.
func (m *MockSubscriptionService) ListSubscriptionPlans(ctx context.Context, pagination *dtos.Pagination) ([]*models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubscriptionPlans", ctx, pagination)
	ret0, _ := ret[0].([]*models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubscriptionPlans indicates an expected call of ListSubscriptionPlans.
func (mr *MockSubscriptionServiceMockRecorder) ListSubscriptionPlans(ctx, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubscriptionPlans", reflect.TypeOf((*MockSubscriptionService)(nil).ListSubscriptionPlans), ctx, pagination)
}

// UpdateSubscriptionPlan mocks base method.
func (m *MockSubscriptionService) UpdateSubscriptionPlan(ctx context.Context, id string, subscription *models.Subscription) (*models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionPlan", ctx, id, subscription)
	ret0, _ := ret[0].(*models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubscriptionPlan indicates an expected call of UpdateSubscriptionPlan.
func (mr *MockSubscriptionServiceMockRecorder) UpdateSubscriptionPlan(ctx, id, subscription interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionPlan", reflect.TypeOf((*MockSubscriptionService)(nil).UpdateSubscriptionPlan), ctx, id, subscription)
}
